### ISSUE TITLE
Do I have to manually enable this theme?

### ISSUE THREAD

**Issue by guihkx** [flathub/org.gtk.Gtk3theme.Materia-dark#2]
I just installed [Flatseal](https://github.com/flathub/com.github.tchx84.Flatseal) and it's not currently using the Materia-Dark theme:

![image](https://user-images.githubusercontent.com/626206/74396379-8958a800-4df0-11ea-960b-9b4ebf8a3205.png)

The theme is installed, but do I have to enable it or...?

```
$ flatpak list | grep -i materia
Name                      Application ID                      Version     Branch  Installation
Materia-dark GTK theme    org.gtk.Gtk3theme.Materia-dark                  3.22    system
```

Not sure if it helps, but:

```
$ flatpak run --command=ls com.github.tchx84.Flatseal -l /usr/share/runtime/share/themes/Materia-dark/gtk-3.0
total 188
drwxr-xr-x 3 nfsnobody nfsnobody   4096 Dec 31  1969 assets
-rw-r--r-- 2 nfsnobody nfsnobody 180094 Dec 28 15:15 gtk.css
-rw-r--r-- 2 nfsnobody nfsnobody   1607 Dec 28 15:15 manifest.json
drwxr-xr-x 4 nfsnobody nfsnobody   4096 Dec 31  1969 share
```

**Comment by TingPing** [comment]
Nope.

How themes are loaded by GTK depends upon your system. On X11 you need an XSettings daemon running. On Wayland you need an up to date `xdg-desktop-portal-gtk` as well as having set the theme in GSettings (usually via a tool like `gnome-tweaks`).

**Comment by guihkx** [comment]
>On X11 you need an XSettings daemon running.

Whoa, thank you. After I installed `xsettingsd` and ran it, the theme did load, indeed! Maybe it's because I'm on KDE and anything GTK-related I configure in `~/.config/gtk-3.0/settings.ini`...?

But I find a bit weird that Flatpak detected that Materia-Dark was enabled and even prompted me to install it, but somehow it still needs XSettings to load the theme. I also had to run `xsettingsd` directly from the terminal because at least on Arch Linux, it doesn't ship with a systemd service unit, so that's a bit awkward too.

Is using XSettings really the only way out?

**Comment by guihkx** [comment]
Okay, just to clear up some of my misunderstandings...

On Plasma 5.18 (because I haven't tested in older versions), after you install `xsettingsd` and re-login, the KDE daemon (`kded5`) should automatically setup a config file for `xsettingsd` in `~/.config/xsettingsd/xsettingsd.conf`, and then it will always run `xsettingsd` for you.

After that, GTK 3 apps in Flatpak should pick up the correct theme.

However, probably due to a bug in Plasma 5.18, the `Net/ThemeName` [property](https://github.com/derat/xsettingsd/wiki/Settings) wasn't being written to `~/.config/xsettingsd/xsettingsd.conf`. Meaning that, for Flatpak apps, I still didn't have a GTK 3 theme set.

The workaround I found, for now, is to manually set `Net/ThemeName`:

```
$ echo 'Net/ThemeName "Materia-dark"' >> ~/.config/xsettingsd/xsettingsd.conf
```

**Comment by TingPing** [comment]
> Is using XSettings really the only way out?

As of today yes. However there is a possibility of `xdg-desktop-portal` replacing XSettings. That discussion could go here: https://github.com/flatpak/xdg-desktop-portal
